# Generated by Django 5.1.2 on 2024-11-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_searchhistory_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='location',
        ),
    ]
