# Generated by Django 5.1.2 on 2024-11-12 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_viewhistory_view_count_alter_searchhistory_keyword'),
        ('listings', '0006_alter_listings_category'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-searched_at']},
        ),
        migrations.AlterModelOptions(
            name='viewhistory',
            options={'ordering': ['-viewed_at']},
        ),
        migrations.RenameField(
            model_name='searchhistory',
            old_name='created_at',
            new_name='searched_at',
        ),
        migrations.RenameField(
            model_name='searchhistory',
            old_name='keyword',
            new_name='term',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='viewhistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='viewhistory',
            name='view_count',
        ),
        migrations.AddField(
            model_name='viewhistory',
            name='viewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to='user.user'),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='listings.listings'),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='user.user'),
        ),
    ]
