# Generated by Django 5.1.2 on 2024-11-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='landlord',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tenant',
            field=models.BooleanField(null=True),
        ),
    ]
