# Generated by Django 5.1.2 on 2024-11-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_landlord_profile_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tenant',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('landlord', 'landlord'), ('tenant', 'tenant')], max_length=20, null=True),
        ),
    ]
