# Generated by Django 5.1.2 on 2024-11-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_location_location_remove_location_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='locations',
        ),
        migrations.AlterModelOptions(
            name='listings',
            options={'ordering': ['-created_at', 'price', 'views'], 'verbose_name': 'Listings'},
        ),
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.SlugField(choices=[('---', '---'), ('***', '***'), ('****', '****'), ('*****', '*****')], default='without category', help_text='enter star category', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='location',
            field=models.CharField(help_text='Landmark (location)', max_length=250, null=True, verbose_name='Where is'),
        ),
        migrations.AddField(
            model_name='listings',
            name='site_link',
            field=models.URLField(help_text='Object page link (https://www.google.de/maps/', max_length=150, null=True, unique=True, verbose_name='Link to page'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image', null=True, upload_to='poster_images/'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='listings',
            table='listings_listings',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
