# Generated by Django 5.1.2 on 2024-11-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listings_locations_alter_listings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.SlugField(choices=[('---', '---'), ('three stars', 'three stars'), ('four stars', 'four stars'), ('five stars', 'five stars')], default='without category', help_text='enter star category', max_length=20, null=True),
        ),
    ]
