# Generated by Django 5.1.2 on 2024-11-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.SlugField(choices=[('without category', 'without category'), ('3-stars', '3-stars'), ('4-stars', '4-stars'), ('5-stars', '5-stars')], default='without category', help_text='enter category star', null=True),
        ),
    ]
