# Generated by Django 5.1.2 on 2024-11-12 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listings_category'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listings',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Listings'},
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='views',
            new_name='number_of_reviews',
        ),
        migrations.AddField(
            model_name='listings',
            name='number_of_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listings',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='user.user'),
        ),
        migrations.AddField(
            model_name='listings',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterModelTable(
            name='listings',
            table=None,
        ),
    ]
