# Generated by Django 5.1.2 on 2024-11-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
